title: "Welcome | 0x5010"
author: Jorge Moreno
url: https://Iokete.github.io
description: >
  Hello! Iâ€™m Jorge Moreno Cano, a Cybersecurity Engineering student specializing in binary and system exploitation. In this blog I will share everything I learn along the way, as well as writeups to challenges I face or new techniques I acquire knowledge of.
permalink: /:slug

favicon: "./favicon.ico"
did_you_mean: false
twitter:
    username: lkt 
    card: summary_large_image

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" 
  appearance_toggle: false 
  back_home_text: "home.." 
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true 
  show_footer: true
  show_copyright: true 
  show_projects: true 
  show_blog: true
  show_old_projects: false
  show_misc_list: false 
  show_reading_time: true 
  show_tags: true 
  home:
    title_projects: "Last Posts"
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
